# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.6-jessie-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install deps
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: lint css
          command: npm run lint:css

      - run:
          name: lint js
          command: npm run lint:js

      - run:
          name: type checking
          command: npm run flow:check

      - run:
          name: type coverage
          command: npm run flow:coverage

      - run:
          name: unit tests + coverage
          command: npm run ci:test:coverage
