import { PaletteType } from '../config/palette';

export interface ButtonTheme {
  errorButtonBackgroundColor: PaletteType;
  errorButtonForegroundColor: PaletteType;
  errorButtonBorderColor: PaletteType;
  errorButtonDisabledBackgroundColor: PaletteType;
  errorButtonDisabledForegroundColor: PaletteType;
  errorButtonDisabledBorderColor: PaletteType;
  errorButtonFocusedBackgroundColor: PaletteType;
  errorButtonFocusedForegroundColor: PaletteType;
  errorButtonFocusedBorderColor: PaletteType;
  errorButtonHoverBackgroundColor: PaletteType;
  errorButtonHoverForegroundColor: PaletteType;
  errorButtonHoverBorderColor: PaletteType;
  minimalButtonBackgroundColor: PaletteType;
  minimalButtonForegroundColor: PaletteType;
  minimalButtonBorderColor: PaletteType;
  minimalButtonDisabledBackgroundColor: PaletteType;
  minimalButtonDisabledForegroundColor: PaletteType;
  minimalButtonDisabledBorderColor: PaletteType;
  minimalButtonFocusedBackgroundColor: PaletteType;
  minimalButtonFocusedForegroundColor: PaletteType;
  minimalButtonFocusedBorderColor: PaletteType;
  minimalButtonHoverBackgroundColor: PaletteType;
  minimalButtonHoverForegroundColor: PaletteType;
  minimalButtonHoverBorderColor: PaletteType;
  primaryButtonBackgroundColor: PaletteType;
  primaryButtonForegroundColor: PaletteType;
  primaryButtonBorderColor: PaletteType;
  primaryButtonDisabledBackgroundColor: PaletteType;
  primaryButtonDisabledForegroundColor: PaletteType;
  primaryButtonDisabledBorderColor: PaletteType;
  primaryButtonFocusedBackgroundColor: PaletteType;
  primaryButtonFocusedForegroundColor: PaletteType;
  primaryButtonFocusedBorderColor: PaletteType;
  primaryButtonHoverBackgroundColor: PaletteType;
  primaryButtonHoverForegroundColor: PaletteType;
  primaryButtonHoverBorderColor: PaletteType;
  secondaryButtonBackgroundColor: PaletteType;
  secondaryButtonForegroundColor: PaletteType;
  secondaryButtonBorderColor: PaletteType;
  secondaryButtonDisabledBackgroundColor: PaletteType;
  secondaryButtonDisabledForegroundColor: PaletteType;
  secondaryButtonDisabledBorderColor: PaletteType;
  secondaryButtonFocusedBackgroundColor: PaletteType;
  secondaryButtonFocusedForegroundColor: PaletteType;
  secondaryButtonFocusedBorderColor: PaletteType;
  secondaryButtonHoverBackgroundColor: PaletteType;
  secondaryButtonHoverForegroundColor: PaletteType;
  secondaryButtonHoverBorderColor: PaletteType;
  successButtonBackgroundColor: PaletteType;
  successButtonForegroundColor: PaletteType;
  successButtonBorderColor: PaletteType;
  successButtonDisabledBackgroundColor: PaletteType;
  successButtonDisabledForegroundColor: PaletteType;
  successButtonDisabledBorderColor: PaletteType;
  successButtonFocusedBackgroundColor: PaletteType;
  successButtonFocusedForegroundColor: PaletteType;
  successButtonFocusedBorderColor: PaletteType;
  successButtonHoverBackgroundColor: PaletteType;
  successButtonHoverForegroundColor: PaletteType;
  successButtonHoverBorderColor: PaletteType;
}

export const defaultButtonTheme: ButtonTheme = {
  errorButtonBackgroundColor: 'red600',
  errorButtonForegroundColor: 'white',
  errorButtonBorderColor: 'red600',
  errorButtonDisabledBackgroundColor: 'red200',
  errorButtonDisabledForegroundColor: 'white',
  errorButtonDisabledBorderColor: 'red200',
  errorButtonFocusedBackgroundColor: 'red800',
  errorButtonFocusedForegroundColor: 'white',
  errorButtonFocusedBorderColor: 'red800',
  errorButtonHoverBackgroundColor: 'red700',
  errorButtonHoverForegroundColor: 'white',
  errorButtonHoverBorderColor: 'red700',
  minimalButtonBackgroundColor: 'white',
  minimalButtonForegroundColor: 'blue600',
  minimalButtonBorderColor: 'grey100',
  minimalButtonDisabledBackgroundColor: 'white',
  minimalButtonDisabledForegroundColor: 'blue200',
  minimalButtonDisabledBorderColor: 'grey000',
  minimalButtonFocusedBackgroundColor: 'blue200',
  minimalButtonFocusedForegroundColor: 'blue900',
  minimalButtonFocusedBorderColor: 'blue200',
  minimalButtonHoverBackgroundColor: 'blue000',
  minimalButtonHoverForegroundColor: 'blue800',
  minimalButtonHoverBorderColor: 'blue000',
  primaryButtonBackgroundColor: 'blue600',
  primaryButtonForegroundColor: 'white',
  primaryButtonBorderColor: 'blue600',
  primaryButtonDisabledBackgroundColor: 'blue200',
  primaryButtonDisabledForegroundColor: 'white',
  primaryButtonDisabledBorderColor: 'blue200',
  primaryButtonFocusedBackgroundColor: 'blue800',
  primaryButtonFocusedForegroundColor: 'white',
  primaryButtonFocusedBorderColor: 'blue800',
  primaryButtonHoverBackgroundColor: 'blue700',
  primaryButtonHoverForegroundColor: 'white',
  primaryButtonHoverBorderColor: 'blue700',
  secondaryButtonBackgroundColor: 'grey600',
  secondaryButtonForegroundColor: 'white',
  secondaryButtonBorderColor: 'grey600',
  secondaryButtonDisabledBackgroundColor: 'grey200',
  secondaryButtonDisabledForegroundColor: 'white',
  secondaryButtonDisabledBorderColor: 'grey200',
  secondaryButtonFocusedBackgroundColor: 'grey800',
  secondaryButtonFocusedForegroundColor: 'white',
  secondaryButtonFocusedBorderColor: 'grey800',
  secondaryButtonHoverBackgroundColor: 'grey700',
  secondaryButtonHoverForegroundColor: 'white',
  secondaryButtonHoverBorderColor: 'grey700',
  successButtonBackgroundColor: 'green600',
  successButtonForegroundColor: 'white',
  successButtonBorderColor: 'green600',
  successButtonDisabledBackgroundColor: 'green200',
  successButtonDisabledForegroundColor: 'white',
  successButtonDisabledBorderColor: 'green200',
  successButtonFocusedBackgroundColor: 'green800',
  successButtonFocusedForegroundColor: 'white',
  successButtonFocusedBorderColor: 'green800',
  successButtonHoverBackgroundColor: 'green700',
  successButtonHoverForegroundColor: 'white',
  successButtonHoverBorderColor: 'green700',
};
