/* eslint-disable sort-keys */
import palette from './palette'

export default {
  e2e: true,
  palette,
  fontPrimary: "'IBM Plex Sans', 'Helvetica Neue', Arial, sans-serif;",
  brandNameColor: palette.gray3,
  buttonBackgroundColor: palette.orient,
  buttonBorderRadius: '0.125rem',
  buttonColor: palette.white,
  buttonHoverColor: palette.ocean,
  cartridgeBackgroundColor: palette.cerulean,
  cartridgeColor: palette.white,
  circleBadgeColor: palette.white,
  circleBadgeBackgroundColor: palette.gray2,
  circleBadgeHoverColor: palette.orient,
  dangerColor: palette.red,
  dropdownColor: palette.gray5,
  dropdownArrowColor: palette.gray5,
  footerCategoryColor: palette.gray7,
  iconColor: palette.gray5,
  iconHoverColor: palette.gray4,
  inputBackgroundColor: palette.white,
  inputBorderColor: palette.gray2,
  inputBorderRadius: '0.125rem',
  inputCheckboxColor: palette.cerulean,
  inputColor: palette.gray5,
  inputPlaceholderColor: palette.gray3,
  linkColor: palette.gray5,
  linkHoverColor: palette.orient,
  loaderColor: palette.cerulean,
  navbarDropdownContentBackgroundColor: palette.white,
  navbarDropdownContentBorderColor: palette.gray3,
  navbarDropdownContentShadowColor: palette.blackAlpha25,
  navbarDropdownContentShadowColor2: palette.blackAlpha10,
  navbarDropdownDescriptionColor: palette.gray3,
  navbarDropdownDescriptionMobileColor: palette.whiteAlpha50,
  navbarDropdownHeaderColor: palette.white,
  navbarDropdownTitleColor: palette.azure,
  navbarDropdownTitleMobileColor: palette.white,
  navbarMenuBagroundColor: palette.orient,
  navbarTogglerColor: palette.white,
  paginationBackgroundColor: palette.transparent,
  paginationBorderColor: palette.gray1,
  paginationColor: palette.gray6,
  paginationHoverBackgroundColor: palette.ceruleanAlpha10,
  paginationHoverColor: palette.gray6,
  paginationSelectedBackgroundColor: palette.cerulean,
  paginationSelectedColor: palette.white,
  panelBackgroundColor: palette.white,
  panelShadowColor: palette.gray1,
  searchBarShadowColor: palette.blackAlpha50,
  searchBarBackgroundColor: palette.white,
  searchBarIconColor: palette.black,
  searchBarSubmitColor: palette.black,
  searchBarSubmitHoverBackgroundColor: palette.royal,
  searchBarSubmitBackgroundColor: palette.gold,
  searchBarUnderlinedBackgroundColor: palette.transparent,
  searchBarUnderlinedBorderColor: palette.gray2,
  sectionBackgroundColor: palette.transparent,
  successColor: palette.green,
  tableCellEvenBackgroundColor: palette.gray0,
  tableCellOddBackgroundColor: palette.white,
  tableShadowColor: palette.gray1,
  tabMenuBarColor: palette.gold,
  tabMenuBorderColor: palette.gray1,
  textColor: palette.gray5,
  toastBackgroundColor: palette.white,
  toastBorderRadius: '0.125rem',
  toastTextColor: palette.black,
  togglerBackgroundColor: palette.white,
  togglerBorderColor: palette.gray1,
  togglerColor: palette.cerulean,
  togglerSelectedBackgroundColor: palette.cerulean,
  togglerSelectedColor: palette.white,
  tooltipBackgroundColor: palette.gray6,
  tooltipBorderColor: palette.gray6,
  tooltipColor: palette.white,
  warningColor: palette.yellow,
}
/* eslint-enable sort-keys */
