import palette from './palette'
import { lighten } from 'polished'
/* eslint-disable sort-keys */
export default {
  palette,
  fontPrimary: "'IBM Plex Sans', 'Helvetica Neue', Arial, sans-serif;",
  buttonColor: palette['white'],
  buttonBackgroundColor: palette['orient'],
  buttonHoverColor: lighten(0.1, palette['orient']),
  cartridgeColor: palette['white'],
  cartridgeBackgroundColor: palette['orient'],
  circleBadgeBackgroundColor: palette['gray2'],
  circleBadgeHoverColor: palette['orient'],
  dropdownColor: palette['gray5'],
  dropdownBackgroundColor: palette['transparent'],
  footerCategoryColor: palette['gray6'],
  iconColor: palette['gray5'],
  iconHoverColor: palette['gray4'],
  inputColor: palette['gray5'],
  inputBackgroundColor: palette['white'],
  inputBorderColor: palette['gray2'],
  inputPlaceholderColor: palette['gray3'],
  linkColor: palette['gray5'],
  linkHoverColor: palette['orient'],
  navbarDropdownContentBackgroundColor: palette['white'],
  navbarDropdownContentShadowColor: palette['gray5'],
  navbarDropdownHeaderColor: palette['white'],
  navbarMenuBagroundColor: palette['orient'],
  navbarTogglerColor: palette['white'],
  paginationBorderColor: palette['gray1'],
  paginationColor: palette['gray6'],
  paginationBackgroundColor: palette['transparent'],
  paginationHoverColor: palette['gray6'],
  paginationHoverBackgroundColor: palette['ceruleanAlpha10'],
  paginationSelectedColor: palette['white'],
  paginationSelectedBackgroundColor: palette['cerulean'],
  panelBackgroundColor: palette['white'],
  panelShadowColor: palette['gray1'],
  searchBarInputBackgroundColor: palette['white'],
  searchBarIconBackgroundColor: palette['gold'],
  searchBarUnderlinedBackgroundColor: palette['transparent'],
  searchBarUnderlinedBorderColor: palette['gray2'],
  sectionBackgroundColor: palette['transparent'],
  tableShadowColor: palette['gray1'],
  tableCellEvenBackgroundColor: palette['gray0'],
  tableCellOddBackgroundColor: palette['white'],
  tabMenuBorderColor: palette['gray1'],
  tabMenuBarColor: palette['gold'],
  textColor: palette['gray5'],
  togglerBorderColor: palette['gray1'],
  togglerColor: palette['cerulean'],
  togglerBackgroundColor: palette['white'],
  togglerSelectedColor: palette['white'],
  togglerSelectedBackgroundColor: palette['cerulean'],
  tooltipColor: palette['white'],
  tooltipBackgroundColor: palette['gray6'],
  tooltipBorderColor: palette['gray6'],
}
/* eslint-enable */
